### ISSUE TITLE
Issue even running an example script

### ISSUE THREAD

**Issue by ghost** [matias-kovero/tarkov#25]
Hey,

My nodeJS is a bit rusty and I was running into some issues which I don't believe stem from any recent code changes but something to do with my node install. 

I'm running node version v8.9.4

I did a git clone on the repo, I went into the repo and ran a ```npm install``` and it downloaded from what I can tell all of the node_modules required.

Default code file i'm trying to run (expecting it to at least fail inside of here) named it ```tarkov_test.js```

```const { Tarkov } = require('tarkov');

// We can either provide a pre-generated hwid, or not pass it to Tarkov() for a randomly generated one
const hwid = 'awesome-sick-hwid';
const t = new Tarkov(hwid);

// Run everything in an async function
(async () => {

  // Login to tarkov, optionally also pass 2 factor code as a third param
  t.login('email@email.com', 'password');

  // Load all profiles we have
  const profiles = await t.getProfiles();

  // We're just going to grab the second profile
  const profile = await t.selectProfile(profiles[1]);

  // Load our i18n translations
  await t.getI18n('en');
})();
```

I then try to run it using **node tarkov_test.js**

I get the following error:

```~\node_modules\got\dist\source\create.js:101
    got.paginate = async function* (url, options) {
                                 ^

SyntaxError: Unexpected token *
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:607:28)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (~\node_modules\got\dist\source\index.js:7:18)
```

**Comment by matias-kovero** [comment]
@Ryan24578 If you are cloning the repo, you don't have the built package -> 
You need to build it yourself by using `npm build`.

The easy way: 
Use npm itself to load the already built package with `npm install tarkov`

**Comment by ghost** [comment]
This is the error i'm getting after doing `npm install tarkov` 

I create the script inside of the directory above `node_modules/`  so it looks like this

> $ ls
> node_modules/  package-lock.json  test.js

I then run `node test.js` 

and get this error

```
~\tarkov_test\node_modules\got\dist\source\create.js:101
    got.paginate = async function* (url, options) {
                                 ^

SyntaxError: Unexpected token *
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:607:28)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (~\tarkov_test\node_modules\got\dist\source\index.js:7:18)

```
Node version: v8.9.4
NPM version: 5.6.0

`test.js` simply contains the example script that's in the ReadMe of this repo, I expect it to fail obviously on the script itself but this seems like some sort of node error with the `got` package being downloaded.

**Comment by CodeWithBryan** [comment]
Upgrade above node v 11.7.0+ and try again, I suggest 12.13.x LTS

**Comment by ghost** [comment]
That looks like it's working, thanks ! :)
