### ISSUE TITLE
Missing dependancies

### ISSUE THREAD

**Issue by devolution2409** [matias-kovero/tarkov#8]
Hello, after installing your package using npm, i wanted to use the generate_hwid() function, i got the following message:
```Error: Cannot find module 'request'
Require stack:
- /source/node_modules/request-promise-native/lib/rp.js
- /source/node_modules/tarkov/lib/globals.js
- /source/node_modules/tarkov/index.js
- /source/build/index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:980:15)
    at Function.Module._load (internal/modules/cjs/loader.js:862:27)
    at Module.require (internal/modules/cjs/loader.js:1040:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at /source/node_modules/request-promise-native/lib/rp.js:8:12
    at module.exports (/source/node_modules/stealthy-require/lib/index.js:62:23)
    at Object.<anonymous> (/source/node_modules/request-promise-native/lib/rp.js:7:15)
    at Module._compile (internal/modules/cjs/loader.js:1151:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1171:10)
    at Module.load (internal/modules/cjs/loader.js:1000:32) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/source/node_modules/request-promise-native/lib/rp.js',
    '/source/node_modules/tarkov/lib/globals.js',
    '/source/node_modules/tarkov/index.js',
    '/source/build/index.js'
  ]
}
```

fixed by using npm i request.

**Comment by matias-kovero** [comment]
When you use `npm i tarkov` it will inform you to _install peer dependencies_ yourself, request is one of them.

This api is currently being ported to Typescript and this shoudn't be an issue later on.

**Comment by matias-kovero** [comment]
Added `Request` to dependencies. As request no longer getting support, looking for a package that will replace it. Closing this issue for now.
